FROM unidata/thredds-docker:5.9

# Bake in a minimal, generic catalog.
# Mount /data/* volumes at runtime.
COPY thredds-config/catalog.xml /usr/local/tomcat/content/thredds/catalog.xml
COPY thredds-config/threddsConfig.xml /usr/local/tomcat/content/thredds/threddsConfig.xml

