server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index pdp-next-viewer.html;

  location = /favicon.ico {
    log_not_found off;
    access_log off;
  }
 
  location /portal-meta/ {
    alias /portal-meta/;
    default_type application/json;
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /pdp-next-viewer.html;
  }
}
